[package]
authors = ["KENTARO OKUDA <lonesometraveler@mac.com>"]
edition = "2018"
readme = "README.md"
name = "maxbotix"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
max6955 = "0.1.3"
heapless = "0.5.4"

[dependencies.stm32f4xx-hal]
version = "0.7"
features = ["rt", "stm32f429"] # replace the model of your microcontroller here

[lib]
name = "maxsonar"
path = "src/lib.rs"

# Uncomment for the panic example.
# panic-itm = "0.4.1"

# Uncomment for the allocator example.
# alloc-cortex-m = "0.3.5"

# Uncomment for the device example.
# Update `memory.x`, set target to `thumbv7em-none-eabihf` in `.cargo/config`,
# and then use `cargo build --examples device` to build it.
# [dependencies.stm32f3]
# features = ["stm32f303", "rt"]
# version = "0.7.1"

# this lets you use `cargo fix`!
[[bin]]
name = "maxbotix"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
